version: '3.9'

services:
  db:
    image: postgres:17.5
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
      TZ: America/Bogota
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/secure_vault
      JWT_SECRET: supersecurejwtsecret
      SMTP_HOST: smtp.sendgrid.net
      SMTP_PORT: 465
      SMTP_USER: apikey
      SMTP_PASS: your_smtp_password
      EMAIL_FROM: noreply@securevault.com
      FRONTEND_URL: http://localhost:3000
      AWS_REGION: us-east-1
      KMS_KEY_ID: alias/secure-vault-kms
      
volumes:
  postgres_data:
